"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {OrbitControls,PerspectiveCamera,Environment,Html} from "@react-three/drei";
import {Physics,RigidBody,BoxCollider} from "@react-three/rapier";
import {useRef,useState} from "react";
import * as THREE from "three";

function Building({position,color,onClick}:{position:[number,number,number];color:string;onClick:()=>void}){return <RigidBody type="fixed" colliders="cuboid"><mesh position={[position[0],1.5,position[2]]} onClick={e=>{e.stopPropagation();onClick()}} castShadow receiveShadow><boxGeometry args={[3,3,3]}/><meshStandardMaterial color={color} roughness={.9}/></mesh></RigidBody>}
function Player(){const ref=useRef<any>(null);useFrame((_,d)=>{if(ref.current){const p=ref.current.translation();ref.current.setTranslation({x:p.x,y:1,z:p.z},true)}});return <RigidBody ref={ref} colliders="cuboid" position={[0,1,0]}><mesh castShadow><boxGeometry args={[.8,1.8,.8]}/><meshStandardMaterial color="#26334a"/></mesh></RigidBody>}
function World({onBusiness}:{onBusiness:()=>void}){return <><ambientLight intensity={1.8}/><directionalLight position={[10,18,8]} intensity={3} castShadow shadow-mapSize-width={2048} shadow-mapSize-height={2048}/><mesh rotation-x={-Math.PI/2} receiveShadow><planeGeometry args={[60,60]}/><meshStandardMaterial color="#78966d"/></mesh>{Array.from({length:7},(_,i)=><mesh key={i} position={[-18+i*6,.025,0]} rotation-x={-Math.PI/2}><planeGeometry args={[3,60]}/><meshStandardMaterial color="#41474e"/></mesh>)}<Building position={[-9,1.5,-9]} color="#8b72a8" onClick={()=>{}}/><Building position={[-3,1.5,-9]} color="#c47b69" onClick={()=>{}}/><Building position={[9,1.5,-9]} color="#5d91a8" onClick={()=>{}}/><Building position={[-9,1.5,7]} color="#d1ad61" onClick={()=>{}}/><Building position={[9,1.5,7]} color="#6ca99b" onClick={()=>{}}/><RigidBody type="fixed" colliders="cuboid"><mesh position={[3,1.25,3]} castShadow onClick={e=>{e.stopPropagation();onBusiness()}}><boxGeometry args={[3.5,2.5,3.5]}/><meshStandardMaterial color="#d9f56a" roughness={.75}/></mesh><Html position={[0,2.1,0]} center><div style={{background:'#17221c',color:'#d9f56a',padding:'6px 9px',borderRadius:6,fontWeight:800,fontSize:12}}>YOUR BUSINESS</div></Html></RigidBody><Player/></>}
export default function Game(){const [cash,setCash]=useState(10000);const [level,setLevel]=useState(1);const [notice,setNotice]=useState('Click your business to start');const upgrade=()=>{setCash(c=>c+500);setLevel(l=>l+1);setNotice('Business upgraded • +₱500 revenue')};return <main style={{width:'100vw',height:'100vh',background:'#87b6d0'}}><Canvas shadows dpr={1} gl={{antialias:false}}><PerspectiveCamera makeDefault position={[18,20,18]} fov={38}/><Environment preset="park"/><Physics gravity={[0,-9.81,0]}><World onBusiness={upgrade}/></Physics><OrbitControls enablePan={false} minDistance={12} maxDistance={35} minPolarAngle={.65} maxPolarAngle={1.25}/></Canvas><div style={{position:'absolute',top:16,left:16,right:16,display:'flex',justifyContent:'space-between',pointerEvents:'none'}}><div style={{background:'#111827ee',padding:'12px 16px',borderRadius:10,fontWeight:900,letterSpacing:1}}>STARTUP TYCOON</div><div style={{background:'#111827ee',padding:'12px 16px',borderRadius:10,fontWeight:800}}>₱{cash.toLocaleString()} &nbsp; • &nbsp; BUSINESS LV.{level}</div></div><div style={{position:'absolute',bottom:20,left:'50%',transform:'translateX(-50%)',background:'#d9f56a',color:'#17221c',padding:'12px 18px',borderRadius:10,fontWeight:800}}>{notice}</div></main>}
