"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {OrbitControls,Environment,Html} from "@react-three/drei";
import {Physics,RigidBody} from "@react-three/rapier";
import {useEffect,useRef,useState} from "react";
import * as THREE from "three";

function City({onShop}:{onShop:()=>void}){const player=useRef<any>(null);const keys=useRef<Record<string,boolean>>({});useEffect(()=>{const d=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=true;const u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;addEventListener("keydown",d);addEventListener("keyup",u);return()=>{removeEventListener("keydown",d);removeEventListener("keyup",u)}},[]);useFrame(()=>{if(!player.current)return;const k=keys.current;let x=0,z=0;if(k.w||k.arrowup)z-=1;if(k.s||k.arrowdown)z+=1;if(k.a||k.arrowleft)x-=1;if(k.d||k.arrowright)x+=1;const v=new THREE.Vector3(x,0,z);if(v.lengthSq())v.normalize().multiplyScalar(4);player.current.setLinvel({x:v.x,y:0,z:v.z},true)});return <><ambientLight intensity={1.7}/><directionalLight position={[12,20,10]} intensity={3} castShadow/><mesh rotation-x={-Math.PI/2} receiveShadow><planeGeometry args={[70,70]}/><meshStandardMaterial color="#7f9b72"/></mesh>{[-12,-6,0,6,12].map(x=><mesh key={x} position={[x,.03,0]} rotation-x={-Math.PI/2}><planeGeometry args={[3.2,60]}/><meshStandardMaterial color="#3f454c"/></mesh>)}{Array.from({length:14},(_,i)=>{const x=(i%7)*6-18,z=Math.floor(i/7)*14-7;return <RigidBody key={i} type="fixed" colliders="cuboid"><mesh position={[x,1.5,z]} castShadow><boxGeometry args={[3.4,3,3.4]}/><meshStandardMaterial color={['#9b78a8','#c98270','#6593aa','#d1ad62','#6aa18f'][i%5]} roughness={.85}/></mesh></RigidBody>})}<RigidBody type="fixed" colliders="cuboid"><mesh position={[6,1.25,8]} castShadow onClick={e=>{e.stopPropagation();onShop()}}><boxGeometry args={[4,2.5,4]}/><meshStandardMaterial color="#d9f56a"/></mesh><Html position={[0,2.1,0]} center><div style={{background:'#17221c',color:'#d9f56a',padding:'7px 10px',borderRadius:7,fontWeight:900,fontSize:12,whiteSpace:'nowrap'}}>YOUR STARTUP</div></Html></RigidBody><RigidBody ref={player} position={[0,1,10]} colliders="cuboid"><mesh castShadow><boxGeometry args={[.9,1.8,.9]}/><meshStandardMaterial color="#252d42"/></mesh></RigidBody></>}
export default function Game(){const [cash,setCash]=useState(10000);const [level,setLevel]=useState(1);const [notice,setNotice]=useState('Tap YOUR STARTUP to begin');const upgrade=()=>{setCash(v=>v+500);setLevel(v=>v+1);setNotice('Business upgraded  •  +₱500 revenue')};return <main style={{height:'100dvh',width:'100vw',position:'relative',background:'#87b6d0',overflow:'hidden',touchAction:'none'}}><Canvas shadows dpr={[1,1.5]} gl={{antialias:false}} camera={{position:[20,22,20],fov:35}}><Environment preset="park"/><Physics gravity={[0,-9.81,0]}><City onShop={upgrade}/></Physics><OrbitControls enablePan={false} minDistance={12} maxDistance={38} minPolarAngle={.65} maxPolarAngle={1.2} enableDamping dampingFactor={.08}/></Canvas><div style={{position:'absolute',top:'max(10px,env(safe-area-inset-top))',left:10,right:10,display:'flex',justifyContent:'space-between',gap:8,pointerEvents:'none',fontSize:'clamp(11px,3.2vw,16px)'}}><b style={{background:'#111827ee',padding:'10px 12px',borderRadius:10}}>STARTUP TYCOON</b><b style={{background:'#111827ee',padding:'10px 12px',borderRadius:10}}>₱{cash.toLocaleString()} • LV {level}</b></div><div style={{position:'absolute',bottom:'max(12px,env(safe-area-inset-bottom))',left:'50%',transform:'translateX(-50%)',background:'#d9f56a',color:'#17221c',padding:'11px 14px',borderRadius:10,fontWeight:900,textAlign:'center',fontSize:'clamp(10px,3vw,14px)',width:'min(94vw,560px)'}}>{notice}<br/><span style={{fontWeight:600}}>Desktop: WASD/arrows • Mobile: drag to look, tap your business</span></div></main>}
