"use client";
import {useEffect,useRef,useState} from "react";
import * as THREE from "three";

export default function Game(){
 const ref=useRef<HTMLDivElement>(null);const [cash,setCash]=useState(10000);const [shops,setShops]=useState(1);const [message,setMessage]=useState("Build your first business");
 useEffect(()=>{if(!ref.current)return;const el=ref.current;const scene=new THREE.Scene();scene.background=new THREE.Color(0x8ecae6);const camera=new THREE.OrthographicCamera(-16,16,9,-9,.1,100);camera.position.set(18,18,18);camera.lookAt(0,0,0);const renderer=new THREE.WebGLRenderer({antialias:false});renderer.setPixelRatio(1);renderer.setSize(el.clientWidth,el.clientHeight);el.appendChild(renderer.domElement);
 const light=new THREE.HemisphereLight(0xffffff,0x405040,2);scene.add(light);const ground=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshLambertMaterial({color:0x6f8f68}));ground.rotation.x=-Math.PI/2;scene.add(ground);
 for(let x=-15;x<=15;x+=4){const road=new THREE.Mesh(new THREE.BoxGeometry(2,.05,40),new THREE.MeshLambertMaterial({color:0x3b4148}));road.position.x=x;scene.add(road)}
 const makeBuilding=(x:number,z:number,color:number)=>{const b=new THREE.Mesh(new THREE.BoxGeometry(3,THREE.MathUtils.randInt(2,5),3),new THREE.MeshLambertMaterial({color}));b.position.set(x,b.geometry.parameters.height/2,z);scene.add(b)};
 [[-7,-7,0x9b5de5],[-2,-7,0xf15bb5],[7,-7,0x00bbf9],[-7,6,0xfee440],[8,6,0x00f5d4]].forEach(v=>makeBuilding(v[0],v[1],v[2]));
 const shop=new THREE.Mesh(new THREE.BoxGeometry(3,2.5,3),new THREE.MeshLambertMaterial({color:0xd9f56a}));shop.position.set(2,1.25,2);shop.userData.shop=true;scene.add(shop);
 const player=new THREE.Mesh(new THREE.BoxGeometry(.8,1.4,.8),new THREE.MeshLambertMaterial({color:0x22223b}));player.position.set(0,.7,0);scene.add(player);
 const pointer=new THREE.Vector2();const ray=new THREE.Raycaster();const onClick=(e:MouseEvent)=>{const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(shop)[0];if(hit){setCash(c=>c+350);setShops(s=>s+1);setMessage("Business upgraded. +₱350 revenue")}};renderer.domElement.addEventListener("click",onClick);let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);shop.rotation.y+=.003;renderer.render(scene,camera)};animate();const resize=()=>renderer.setSize(el.clientWidth,el.clientHeight);window.addEventListener("resize",resize);return()=>{cancelAnimationFrame(frame);window.removeEventListener("resize",resize);renderer.domElement.removeEventListener("click",onClick);renderer.dispose();el.removeChild(renderer.domElement)}},[]);
 return <main style={{width:"100vw",height:"100vh",position:"relative"}}><div ref={ref} style={{position:"absolute",inset:0}}/><header style={{position:"absolute",top:16,left:16,right:16,display:"flex",justifyContent:"space-between",pointerEvents:"none"}}><div style={{background:"#111827ee",padding:"12px 16px",borderRadius:12,fontWeight:800}}>STARTUP TYCOON</div><div style={{background:"#111827ee",padding:"12px 16px",borderRadius:12}}>₱{cash.toLocaleString()} &nbsp; • &nbsp; Businesses {shops}</div></header><div style={{position:"absolute",bottom:20,left:"50%",transform:"translateX(-50%)",background:"#d9f56a",color:"#17221c",padding:"12px 18px",borderRadius:12,fontWeight:800}}>{message}</div></main>
}