"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BriefcaseBusiness, ChartNoAxesCombined, CircleDollarSign, Gauge, Settings, ShoppingBag, Users, Zap } from "lucide-react";
import styles from "./page.module.css";

type Game = { cash:number; revenue:number; expenses:number; customers:number; reputation:number; day:number; inventory:number; staff:number; price:number };
const initial: Game = { cash:12500, revenue:4200, expenses:1750, customers:184, reputation:72, day:14, inventory:68, staff:3, price:18 };

export default function Home() {
  const [g,setG]=useState<Game>(initial);
  const [notice,setNotice]=useState("Your storefront is performing above average.");
  useEffect(()=>{ const saved=localStorage.getItem("startup-tycoon-save"); if(saved) setG(JSON.parse(saved)); },[]);
  useEffect(()=>localStorage.setItem("startup-tycoon-save",JSON.stringify(g)),[g]);
  const profit=g.revenue-g.expenses;
  const margin=Math.round((profit/g.revenue)*100);
  const sell=()=>setG(x=>({...x,cash:x.cash+Math.round(x.price*2.8),revenue:x.revenue+Math.round(x.price*2.8),customers:x.customers+1,inventory:Math.max(0,x.inventory-1)}));
  const operate=()=>{ if(g.inventory<5){setNotice("Inventory is too low. Restock before operating.");return;} setG(x=>({...x,day:x.day+1,cash:x.cash+Math.round(x.revenue*.12)-x.expenses,revenue:Math.round(x.revenue*1.04),expenses:x.expenses+150,customers:x.customers+Math.round(12+x.reputation/10),inventory:Math.max(0,x.inventory-8)})); setNotice("A new business day has been completed."); };
  const upgrade=()=>{if(g.cash<3000){setNotice("You need $3,000 for the next upgrade.");return;}setG(x=>({...x,cash:x.cash-3000,reputation:Math.min(100,x.reputation+8),expenses:x.expenses+75}));setNotice("Store upgrade purchased. Reputation increased.");};
  const hire=()=>{if(g.cash<1800){setNotice("You need $1,800 to hire another employee.");return;}setG(x=>({...x,cash:x.cash-1800,staff:x.staff+1,expenses:x.expenses+280}));setNotice("New employee hired.");};
  const restock=()=>{if(g.cash<600){setNotice("Not enough cash to restock.");return;}setG(x=>({...x,cash:x.cash-600,inventory:Math.min(100,x.inventory+30),expenses:x.expenses+600}));setNotice("Inventory restocked.");};
  const price=useMemo(()=>g.price.toFixed(2),[g.price]);
  return <main className={styles.shell}>
    <aside className={styles.sidebar}><div className={styles.brand}><div className={styles.logo}><BriefcaseBusiness size={19}/></div><div><strong>Startup</strong><span>TYCOON</span></div></div><nav><a className={styles.active}><ChartNoAxesCombined size={18}/>Overview</a><a><ShoppingBag size={18}/>Operations</a><a><Users size={18}/>Team</a><a><Gauge size={18}/>Market</a><a><Zap size={18}/>Upgrades</a></nav><div className={styles.sideBottom}><div className={styles.level}><span>Company level</span><b>03</b></div><div className={styles.progress}><i style={{width:"64%"}}/></div><button className={styles.settings}><Settings size={17}/>Settings</button></div></aside>
    <section className={styles.content}><header><div><p className={styles.eyebrow}>DAY {g.day} · MONDAY</p><h1>Good morning, founder.</h1><p className={styles.sub}>Your business is growing. Keep the momentum.</p></div><button className={styles.next} onClick={operate}>End day <ArrowUpRight size={17}/></button></header>
      <div className={styles.kpis}><Kpi icon={<CircleDollarSign/>} label="Cash balance" value={`$${g.cash.toLocaleString()}`} trend="+12.8%"/><Kpi icon={<ChartNoAxesCombined/>} label="Daily revenue" value={`$${g.revenue.toLocaleString()}`} trend="+8.4%"/><Kpi icon={<Users/>} label="Customers" value={g.customers.toLocaleString()} trend="+16.2%"/><Kpi icon={<Gauge/>} label="Reputation" value={`${g.reputation}/100`} trend="+4.1%"/></div>
      <div className={styles.grid}><section className={styles.card}><div className={styles.cardHead}><div><span className={styles.label}>BUSINESS PERFORMANCE</span><h2>Revenue overview</h2></div><span className={styles.badge}>LIVE</span></div><div className={styles.chart}><div className={styles.chartValue}>${(g.revenue/1000).toFixed(1)}k <small>this week</small></div><svg viewBox="0 0 700 220" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopOpacity=".25"/><stop offset="1" stopOpacity="0"/></linearGradient></defs><path d="M0 190 C55 175 75 120 135 145 S205 165 260 115 S330 140 385 95 S465 120 520 55 S610 95 700 25 L700 220 L0 220Z" fill="url(#fill)"/><path d="M0 190 C55 175 75 120 135 145 S205 165 260 115 S330 140 385 95 S465 120 520 55 S610 95 700 25" fill="none" stroke="currentColor" strokeWidth="3"/></svg></div><div className={styles.chartFoot}><span>MON</span><span>WED</span><span>FRI</span><span>SUN</span></div></section>
      <section className={styles.card}><div className={styles.cardHead}><div><span className={styles.label}>QUICK ACTIONS</span><h2>Run your business</h2></div></div><div className={styles.actions}><Action title="Make a sale" detail="Serve one customer" onClick={sell}/><Action title="Restock" detail={`${g.inventory}% inventory`} onClick={restock}/><Action title="Hire staff" detail={`${g.staff} employees`} onClick={hire}/><Action title="Upgrade store" detail="$3,000 investment" onClick={upgrade}/></div><div className={styles.notice}>{notice}</div></section></div>
      <div className={styles.grid}><section className={styles.card}><div className={styles.cardHead}><div><span className={styles.label}>UNIT ECONOMICS</span><h2>Pricing & margins</h2></div></div><div className={styles.metrics}><Metric label="Selling price" value={`$${price}`} /><Metric label="Profit margin" value={`${margin}%`} /><Metric label="Operating costs" value={`$${g.expenses.toLocaleString()}`} /></div><input className={styles.slider} type="range" min="8" max="35" value={g.price} onChange={e=>setG(x=>({...x,price:+e.target.value}))}/><div className={styles.range}><span>$8</span><span>Price point</span><span>$35</span></div></section><section className={styles.card}><div className={styles.cardHead}><div><span className={styles.label}>COMPANY HEALTH</span><h2>Growth snapshot</h2></div></div><div className={styles.snapshot}><Row label="Inventory" value={`${g.inventory}%`} progress={g.inventory}/><Row label="Team capacity" value={`${Math.min(100,g.staff*25)}%`} progress={Math.min(100,g.staff*25)}/><Row label="Reputation" value={`${g.reputation}%`} progress={g.reputation}/></div></section></div>
    </section></main>
}
function Kpi({icon,label,value,trend}:{icon:React.ReactNode,label:string,value:string,trend:string}){return <div className={styles.kpi}><div className={styles.kpiTop}><span>{icon}</span><small>{trend}</small></div><p>{label}</p><strong>{value}</strong></div>}
function Action({title,detail,onClick}:{title:string,detail:string,onClick:()=>void}){return <button className={styles.action} onClick={onClick}><div><strong>{title}</strong><span>{detail}</span></div><ArrowUpRight size={17}/></button>}
function Metric({label,value}:{label:string,value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Row({label,value,progress}:{label:string,value:string,progress:number}){return <div className={styles.row}><div><span>{label}</span><b>{value}</b></div><div className={styles.progress}><i style={{width:`${progress}%`}}/></div></div>}
