"use client";
import {useEffect,useState} from "react";
import {ArrowRight,Coins,Factory,ShoppingBag,Sparkles,Users,X,Zap,Map,Move,MousePointer2} from "lucide-react";
import styles from "./page.module.css";

type Product={id:string;name:string;icon:string;cost:number;price:number;demand:number};
type Game={cash:number;day:number;inventory:number;reputation:number;customers:number;sales:number;profit:number;staff:number;product:Product|null;tutorial:number;location:string};
const start:Game={cash:10000,day:1,inventory:0,reputation:10,customers:0,sales:0,profit:0,staff:0,product:null,tutorial:0,location:"corner"};
const products:Product[]=[{id:"coffee",name:"Iced Coffee",icon:"coffee",cost:18,price:35,demand:8},{id:"sandwich",name:"Club Sandwich",icon:"sandwich",cost:32,price:65,demand:5},{id:"cake",name:"Cake Slice",icon:"cake",cost:24,price:50,demand:6}];
export default function Home(){
 const[g,setG]=useState(start),[screen,setScreen]=useState<"town"|"shop"|"interior"|"map"|"end">("town"),[toast,setToast]=useState("");
 useEffect(()=>{const s=localStorage.getItem("startup-tycoon");if(s)try{setG(JSON.parse(s))}catch{}},[]);useEffect(()=>localStorage.setItem("startup-tycoon",JSON.stringify(g)),[g]);
 const note=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),1600)};
 const choose=(p:Product)=>{const cost=p.cost*10;if(g.cash<cost)return note("Not enough cash.");setG(x=>({...x,cash:x.cash-cost,inventory:10,product:p,tutorial:2}));setScreen("town");note(`${p.name} stocked. Your shop is ready.`)};
 const sell=()=>{if(!g.product)return note("Choose a product first.");if(!g.inventory)return note("Sold out. Restock.");const p=g.product;setG(x=>({...x,cash:x.cash+p.price,inventory:x.inventory-1,customers:x.customers+1,sales:x.sales+p.price,profit:x.profit+p.price-p.cost,reputation:Math.min(100,x.reputation+.5),tutorial:4}));note(`Sale complete · +₱${p.price}`)};
 const restock=()=>{if(!g.product)return note("Choose a product first.");const cost=g.product.cost*10;if(g.cash<cost)return note("Not enough cash.");setG(x=>({...x,cash:x.cash-cost,inventory:x.inventory+10}));note("10 units delivered to your back room.")};
 const hire=()=>{if(g.cash<1000)return note("Hiring costs ₱1,000.");setG(x=>({...x,cash:x.cash-1000,staff:x.staff+1,reputation:Math.min(100,x.reputation+4)}));note("New employee hired.")};
 const endDay=()=>{if(!g.product)return note("Buy a product first.");const p=g.product,sales=Math.min(g.inventory,Math.max(3,Math.round(p.demand+g.reputation/20))),earned=sales*p.price,cost=sales*p.cost+120+g.staff*80;setG(x=>({...x,day:x.day+1,cash:x.cash+earned-cost,inventory:x.inventory-sales,customers:x.customers+sales,sales:x.sales+earned,profit:x.profit+earned-cost,tutorial:6}));setScreen("end")};
 const reset=()=>{localStorage.removeItem("startup-tycoon");setG(start);setScreen("town")};
 return <main className={styles.game}>
  <header className={styles.topbar}><div className={styles.logo}><span>ST</span> STARTUP TYCOON</div><div className={styles.day}>DAY {g.day}</div><div className={styles.money}><Coins/>₱{g.cash.toLocaleString()}</div></header>
  {screen==="town"&&<section className={styles.world}><div className={styles.sky}><div className={styles.sun}/><div className={`${styles.cloud} ${styles.cloud1}`}/><div className={`${styles.cloud} ${styles.cloud2}`}/></div><div className={styles.city}><div className={`${styles.building} ${styles.b1}`}/><div className={`${styles.building} ${styles.b2}`}/><div className={`${styles.building} ${styles.b3}`}/><span className={styles.tree}/><span className={`${styles.tree} ${styles.tree2}`}/></div><div className={styles.road}/>
   <button className={styles.shopBuilding} onClick={()=>setScreen("interior")}><img src="/assets/shop.svg" alt="Your Corner Cafe" className={styles.shopArt}/></button>
   {g.customers>0&&Array.from({length:Math.min(9,g.customers)}).map((_,i)=><img src="/assets/customer.svg" className={styles.personArt} alt="customer" key={i} style={{left:`${16+i*9}%`,animationDelay:`${i*.2}s`}}/>)}
   {g.product&&g.inventory>0&&<button className={styles.customerBubble} onClick={sell}><span>A customer is ready</span><b><ProductIcon type={g.product.icon}/>{g.product.name}</b><strong>SELL +₱{g.product.price}</strong></button>}
   <div className={styles.hud}><Stat label="REPUTATION" value={`${Math.round(g.reputation)}/100`} pct={g.reputation}/><Stat label="INVENTORY" value={String(g.inventory)} pct={Math.min(100,g.inventory*10)}/><Stat label="STAFF" value={String(g.staff)} pct={Math.min(100,g.staff*25)}/></div>
   <button className={styles.mapButton} onClick={()=>setScreen("map")}><Map/>CITY MAP</button>
  </section>}
  {screen==="interior"&&<Interior g={g} setScreen={setScreen} note={note}/>} {screen==="map"&&<CityMap setScreen={setScreen} note={note}/>} {screen==="shop"&&<Shop products={products} g={g} choose={choose} close={()=>setScreen("town")}/>} 
  {screen==="end"&&<div className={styles.overlay}><div className={styles.endcard}><div className={styles.endIcon}><Zap/></div><small className={styles.kicker}>DAY COMPLETE</small><h1>Day {g.day-1} is over.</h1><div className={styles.results}><Result label="Revenue" value={`₱${g.sales.toLocaleString()}`}/><Result label="Customers" value={String(g.customers)}/><Result label="Lifetime profit" value={`₱${g.profit.toLocaleString()}`}/></div><p>{g.profit>=0?"The shop survived its first day. Now scale it into something bigger.":"Your first day was rough. Change your strategy and try again."}</p><button className={styles.primaryBig} onClick={()=>setScreen("town")}>Start Day {g.day}<ArrowRight/></button><button className={styles.reset} onClick={reset}>Reset save</button></div></div>}
  {screen==="town"&&<footer className={styles.controls}><div className={styles.goal}><Sparkles/><div><small>NEXT OBJECTIVE</small><b>{g.tutorial<2?"Buy your first product":g.tutorial<4?"Make your first sale":g.tutorial<6?"Finish the day":"Grow the company"}</b></div></div><div className={styles.actions}><button onClick={()=>setScreen("shop")}><ShoppingBag/>Shop</button><button onClick={restock} disabled={!g.product}><Factory/>Restock</button><button onClick={hire}><Users/>Hire</button><button className={styles.primary} onClick={endDay}>End Day <ArrowRight/></button></div></footer>}
  {g.tutorial<6&&screen==="town"&&<Tutorial step={g.tutorial} goShop={()=>setScreen("shop")} goInterior={()=>setScreen("interior")} sell={sell}/>} {toast&&<div className={styles.toast}>{toast}</div>}
 </main>;
}
function Tutorial({step,goShop,goInterior,sell}:{step:number;goShop:()=>void;goInterior:()=>void;sell:()=>void}){const data=step<2?["WELCOME, FOUNDER","You have ₱10,000 and one empty café. Your first goal is simple: get something on the shelf.","BUY YOUR FIRST PRODUCT",goShop]:step<4?["YOUR SHOP IS OPEN","Good choice. Now enter your store and arrange the space. A customer will be waiting outside.","ENTER SHOP",goInterior]:["FIRST SALE","You are now learning the real loop: stock → serve → earn. Click the waiting customer to make the sale.","MAKE SALE",sell];return <div className={styles.tutorial}><div className={styles.tutorialCard}><div className={styles.tutorialTop}><Sparkles/><span>TUTORIAL · {step<2?"01":step<4?"02":"03"}</span></div><h2>{data[0]}</h2><p>{data[1]}</p><button onClick={data[3] as ()=>void}>{data[2]} <ArrowRight/></button></div></div>}
function Shop({products,g,choose,close}:{products:Product[];g:Game;choose:(p:Product)=>void;close:()=>void}){return <div className={styles.overlay}><div className={styles.modal}><button className={styles.close} onClick={close}><X/></button><small className={styles.kicker}>SUPPLIER · DAY {g.day}</small><h1>Stock your shelves</h1><p>Buy a small batch, test demand, then reinvest your profit.</p><div className={styles.products}>{products.map(p=><button className={styles.product} key={p.id} onClick={()=>choose(p)}><span className={styles.productArt}><ProductIcon type={p.icon}/></span><b>{p.name}</b><small>Unit ₱{p.cost} · Sell ₱{p.price}</small><strong>Buy 10 · ₱{p.cost*10}</strong></button>)}</div></div></div>}
function Interior({g,setScreen,note}:{g:Game;setScreen:(s:"town"|"shop"|"interior"|"map"|"end")=>void;note:(s:string)=>void}){const[drag,setDrag]=useState({x:58,y:62});return <section className={styles.interior}><div className={styles.interiorWall}><div className={styles.interiorHeader}><button onClick={()=>setScreen("town")}><ArrowRight/> EXIT</button><div><small>YOUR STORE</small><h1>Corner Café</h1></div><span>₱{g.cash.toLocaleString()}</span></div><div className={styles.floor}><div className={styles.counter}><span>REGISTER</span><b>₱{g.sales}</b></div><button className={styles.shelf} onClick={()=>setScreen("shop")}><span>SHELF · CLICK TO RESTOCK</span><ProductIcon type={g.product?.icon||"coffee"}/><b>{g.inventory} units</b></button><div className={styles.table} style={{left:`${drag.x}%`,top:`${drag.y}%`}} draggable onDragEnd={e=>{const r=e.currentTarget.parentElement!.getBoundingClientRect();setDrag({x:Math.max(20,Math.min(80,(e.clientX-r.left)/r.width*100)),y:Math.max(20,Math.min(80,(e.clientY-r.top)/r.height*100))});note("Table moved.")}}><Move/><span>DRAG ME</span></div><div className={styles.employee}><img src="/assets/customer.svg" alt="employee"/><span>STAFF</span></div></div><div className={styles.interiorHint}><MousePointer2/> Drag the table to rearrange your store. Click the shelf to manage inventory.</div></div></section>}
function CityMap({setScreen,note}:{setScreen:(s:"town"|"shop"|"interior"|"map"|"end")=>void;note:(s:string)=>void}){return <section className={styles.mapScreen}><div className={styles.mapTop}><button onClick={()=>setScreen("town")}><ArrowRight/> BACK</button><div><small>CITY OVERVIEW</small><h1>Maple District</h1></div><span>DAY 1</span></div><div className={styles.mapCanvas}><div className={styles.mapRoads}/><button className={styles.locationPin} style={{left:"48%",top:"48%"}} onClick={()=>setScreen("town")}><b>YOU</b><span>Corner Café</span></button><button className={styles.locationPin} style={{left:"20%",top:"28%"}} onClick={()=>note("Market district unlocks at reputation 25.")}><b>MARKET</b><span>Locked</span></button><button className={styles.locationPin} style={{left:"72%",top:"31%"}} onClick={()=>note("Business district unlocks after your first upgrade.")}><b>OFFICES</b><span>Locked</span></button><button className={styles.locationPin} style={{left:"70%",top:"70%"}} onClick={()=>note("Mall district unlocks later.")}><b>MALL</b><span>Locked</span></button></div><div className={styles.mapLegend}><Map/><div><b>EXPAND YOUR EMPIRE</b><span>New districts unlock as your company grows.</span></div></div></section>}
function ProductIcon({type}:{type:string}){return <span className={`${styles.icon} ${styles[type]}`} aria-hidden="true"/>} function Stat({label,value,pct}:{label:string;value:string;pct:number}){return <div><small>{label}</small><b>{value}</b><div className={styles.bar}><i style={{width:`${pct}%`}}/></div></div>} function Result({label,value}:{label:string;value:string}){return <div><small>{label}</small><b>{value}</b></div>}
